"use client";
import {useEffect,useMemo,useState} from "react";

type Animal={id:string;name:string|null;temporary_name:string|null;species:string|null;breed_or_type:string|null;custody:string|null;urgency:string|null;placement:string|null;photo_url:string|null;open_help_offers:number|string};
const C={navy:"#1E3A5F",coral:"#E85C56",red:"#B9362B",mint:"#DCF0E8",muted:"#4A5D75",border:"#DCE4EC",white:"#FFF"};

export default function Page(){
 const [animals,setAnimals]=useState<Animal[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState<"all"|"critical"|"urgent">("all");
 useEffect(()=>{fetch("/api/animals?caseStatus=active&sort=newest",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error??"Couldn't load urgent animals.");setAnimals(Array.isArray(d.animals)?d.animals:[])}).catch(e=>setError(e instanceof Error?e.message:"Couldn't load urgent animals.")).finally(()=>setLoading(false))},[]);
 const urgent=useMemo(()=>animals.filter(a=>a.urgency==="urgent"||a.urgency==="critical"),[animals]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return urgent.filter(a=>(filter==="all"||a.urgency===filter)&&(!q||[a.name,a.temporary_name,a.species,a.breed_or_type,a.custody,a.placement].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))))},[urgent,filter,search]);
 const critical=urgent.filter(a=>a.urgency==="critical").length,urgentCount=urgent.length-critical;
 return <section style={{maxWidth:980}}>
  <p style={eyebrow}>ANIMALS · NEEDS ATTENTION</p><div style={titleRow}><div><h1 style={heading}>Urgent Animals</h1><p style={intro}>Animals in your care that have been marked Urgent or Critical.</p></div><a href="/animals" style={secondary}>View All Animals</a></div>
  {loading?<section style={empty}>Loading urgent animals…</section>:null}{error?<section role="alert" style={err}>{error}</section>:null}
  {!loading&&!error&&urgent.length===0?<section style={empty}><strong style={{display:"block",marginBottom:5}}>No urgent animals need attention</strong><p style={emptyText}>Animals marked Urgent or Critical during intake or on their animal record will appear here automatically.</p><a href="/animals" style={secondary}>View Animals in Our Care</a></section>:null}
  {!loading&&!error&&urgent.length>0?<><div style={tools}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search urgent animals" aria-label="Search urgent animals" style={searchStyle}/><div style={filters}><Filter active={filter==="all"} onClick={()=>setFilter("all")}>All ({urgent.length})</Filter><Filter active={filter==="critical"} onClick={()=>setFilter("critical")}>Critical ({critical})</Filter><Filter active={filter==="urgent"} onClick={()=>setFilter("urgent")}>Urgent ({urgentCount})</Filter></div></div>
   <p style={results}>Showing {visible.length} of {urgent.length} urgent animals</p>{visible.length===0?<section style={empty}>No urgent animals match this search or filter.</section>:<div style={list}>{visible.map(a=><AnimalCard key={a.id} animal={a}/>)}</div>}</>:null}
 </section>
}
function Filter({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" onClick={onClick} style={{...filterButton,background:active?C.navy:C.white,color:active?C.white:C.navy}}>{children}</button>}
function AnimalCard({animal:a}:{animal:Animal}){const name=a.name||a.temporary_name||"Unnamed animal",offers=Number(a.open_help_offers??0),critical=a.urgency==="critical";return <article style={{...card,borderLeftColor:critical?C.red:C.coral}}><div style={photo}>{a.photo_url?<img src={a.photo_url} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<span aria-hidden="true" style={{fontSize:27}}>🐾</span>}</div><div style={{minWidth:0,flex:1}}><div style={cardHead}><div><h2 style={cardTitle}>{name}</h2><p style={meta}>{[a.species,a.breed_or_type].filter(Boolean).join(" · ")||"Animal details not entered"}</p></div><span style={{...badge,background:critical?"#F8DFDC":"#FFE7DE",color:critical?C.red:"#A7472E"}}>{critical?"CRITICAL":"URGENT"}</span></div><div style={details}><span><strong>Custody:</strong> {format(a.custody)}</span><span><strong>Placement:</strong> {format(a.placement)}</span><span><strong>Open help offers:</strong> {offers}</span></div><div style={actions}><a href={`/animals/${encodeURIComponent(a.id)}`} style={primary}>Open Animal Record</a>{offers>0?<a href={`/animals/${encodeURIComponent(a.id)}/offers`} style={secondary}>Review {offers} Help Offer{offers===1?"":"s"}</a>:null}</div></div></article>}
function format(v:string|null){return v?v.replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase()):"Not entered"}
const eyebrow:React.CSSProperties={margin:"0 0 6px",color:C.coral,fontSize:12,fontWeight:800,letterSpacing:".08em"},titleRow:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:14,flexWrap:"wrap"},heading:React.CSSProperties={margin:"0 0 6px",color:C.navy,fontSize:30},intro:React.CSSProperties={margin:0,maxWidth:780,color:C.muted,fontSize:13.5,lineHeight:1.5},empty:React.CSSProperties={marginTop:16,padding:20,border:`1px solid ${C.border}`,borderRadius:9,background:C.mint,color:C.navy},emptyText:React.CSSProperties={margin:"0 0 13px",color:C.muted,fontSize:13.5,lineHeight:1.5},err:React.CSSProperties={marginTop:16,padding:16,border:"1px solid #E7B6AF",borderRadius:9,background:"#FFF0ED",color:C.red},tools:React.CSSProperties={display:"flex",gap:10,flexWrap:"wrap",alignItems:"center",marginTop:18},searchStyle:React.CSSProperties={flex:"1 1 280px",minWidth:0,padding:"11px 12px",border:`1px solid ${C.border}`,borderRadius:8,fontSize:13.5},filters:React.CSSProperties={display:"flex",gap:7,flexWrap:"wrap"},filterButton:React.CSSProperties={border:`1px solid ${C.border}`,borderRadius:999,padding:"8px 11px",fontSize:12,fontWeight:800,cursor:"pointer"},results:React.CSSProperties={margin:"11px 0 8px",color:C.muted,fontSize:12.5},list:React.CSSProperties={display:"grid",gap:10},card:React.CSSProperties={display:"flex",gap:14,padding:14,border:`1px solid ${C.border}`,borderLeft:"5px solid",borderRadius:9,background:C.white},photo:React.CSSProperties={width:76,height:76,flex:"0 0 76px",borderRadius:8,overflow:"hidden",background:"#F2F5F7",display:"grid",placeItems:"center"},cardHead:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12},cardTitle:React.CSSProperties={margin:0,color:C.navy,fontSize:18},meta:React.CSSProperties={margin:"3px 0 0",color:C.muted,fontSize:12.5},badge:React.CSSProperties={borderRadius:999,padding:"5px 8px",fontSize:10.5,fontWeight:900,letterSpacing:".04em",whiteSpace:"nowrap"},details:React.CSSProperties={display:"flex",gap:"6px 18px",flexWrap:"wrap",marginTop:10,color:C.muted,fontSize:12.5},actions:React.CSSProperties={display:"flex",gap:8,flexWrap:"wrap",alignItems:"center",marginTop:11},primary:React.CSSProperties={display:"inline-block",padding:"8px 11px",borderRadius:7,background:C.navy,color:C.white,fontSize:12,fontWeight:800,textDecoration:"none"},secondary:React.CSSProperties={display:"inline-block",color:C.navy,fontSize:12.5,fontWeight:800,textDecoration:"underline"};
