"use client";
import { useEffect, useState } from "react";

type Submission={id:string;org_name:string;field_label:string;old_value:string;new_value:string};
type Claim={id:string;org_id:string;org_name:string;requester_email:string;created_at:string};
type OrgRequest={id:string;organization_name:string;relationship:string;created_at:string};
type ClaimIssue={id:string;org_name:string;reporter_name:string;reporter_email:string;reporter_phone:string|null;relationship_to_org:string;issue_type:string;previous_org_email:string|null;details:string;evidence_url:string|null;status:string;created_at:string;due_at:string;next_action:string;current_owner_email:string|null;reporter_notified_at:string|null;owner_notified_at:string|null;reporter_evidence_received_at:string|null;owner_response_received_at:string|null;official_record_checked_at:string|null};
type LifecycleReview={id:string;org_id:string;org_name:string;review_type:string;status:string;reason:string;owner_email:string|null;response_due_at:string;created_at:string};
type AdminMember={user_id:string;email:string;access_level:string;status:string;updated_at:string};
type AdminInvite={id:string;email:string;access_level:string;status:string;expires_at:string};

export default function AdminPage(){
  const [submissions,setSubmissions]=useState<Submission[]|null>(null),[claims,setClaims]=useState<Claim[]|null>(null),[orgRequests,setOrgRequests]=useState<OrgRequest[]|null>(null),[claimIssues,setClaimIssues]=useState<ClaimIssue[]|null>(null),[lifecycleReviews,setLifecycleReviews]=useState<LifecycleReview[]>([]);
  const [error,setError]=useState<string|null>(null),[claimActionError,setClaimActionError]=useState<string|null>(null),[notes,setNotes]=useState<Record<string,string>>({}),[working,setWorking]=useState<string|null>(null);
  const [adminTeam,setAdminTeam]=useState<AdminMember[]>([]),[adminInvites,setAdminInvites]=useState<AdminInvite[]>([]),[myAdminLevel,setMyAdminLevel]=useState(""),[inviteEmail,setInviteEmail]=useState(""),[inviteLevel,setInviteLevel]=useState("directory_moderator"),[adminMessage,setAdminMessage]=useState("");
  async function load(){
    setError(null);
    try{
      const accessResponse=await fetch("/api/admin/users/platform",{cache:"no-store"}),accessData=await accessResponse.json();
      if(!accessResponse.ok)throw new Error(accessData.error??"Failed to load the admin team.");
      const level=accessData.currentAccessLevel??"";setAdminTeam(accessData.team??[]);setAdminInvites(accessData.invitations??[]);setMyAdminLevel(level);
      if(level==="platform_owner"||level==="directory_moderator"){
        const [subResponse,requestResponse]=await Promise.all([fetch("/api/admin/submissions",{cache:"no-store"}),fetch("/api/admin/org-requests",{cache:"no-store"})]);
        const subData=await subResponse.json(),requestData=await requestResponse.json();
        if(!subResponse.ok)throw new Error(subData.error??"Failed to load submissions.");if(!requestResponse.ok)throw new Error(requestData.error??"Failed to load organization requests.");
        setSubmissions(subData.submissions??[]);setOrgRequests((requestData.requests??[]).filter((x:any)=>x.status==="pending"));
      }else{setSubmissions([]);setOrgRequests([])}
      if(level==="platform_owner"||level==="case_administrator"){
        const [claimResponse,issueResponse]=await Promise.all([fetch("/api/admin/claims",{cache:"no-store"}),fetch("/api/admin/claim-issues",{cache:"no-store"})]);
        const claimData=await claimResponse.json(),issueData=await issueResponse.json();
        if(!claimResponse.ok)throw new Error(claimData.error??"Failed to load claims.");if(!issueResponse.ok)throw new Error(issueData.error??"Failed to load access cases.");
        setClaims(claimData.claims??[]);setClaimIssues(issueData.reports??[]);setLifecycleReviews(issueData.lifecycleReviews??[]);
      }else{setClaims([]);setClaimIssues([]);setLifecycleReviews([])}
    }catch(e){setError(e instanceof Error?e.message:"The dashboard could not be loaded.")}
  }
  useEffect(()=>{void load()},[]);
  async function act(id:string,action:"approve"|"reject"){await fetch(`/api/admin/submissions/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});load()}
  async function actClaim(id:string,action:"approve"|"reject"){
    setWorking(id);setClaimActionError(null);
    try{
      const response=await fetch("/api/admin/claims",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({claimId:id,action})});
      const data=await response.json();
      if(!response.ok)throw new Error(data.error??`The claim could not be ${action}d.`);
      await load();
    }catch(e){setClaimActionError(e instanceof Error?e.message:"The claim could not be updated.")}
    finally{setWorking(null)}
  }
  async function updateCase(id:string,body:Record<string,string>){setWorking(id);setError(null);const r=await fetch("/api/admin/claim-issues",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({reportId:id,...body})});const d=await r.json();setWorking(null);if(!r.ok){setError(d.error??"The case could not be updated.");return}load()}
  async function inviteAdmin(e:React.FormEvent){e.preventDefault();setWorking("invite-admin");setAdminMessage("");const r=await fetch("/api/admin/users/platform",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:inviteEmail,accessLevel:inviteLevel})});const d=await r.json();setWorking(null);if(!r.ok){setAdminMessage(d.error??"The invitation could not be sent.");return}setInviteEmail("");setAdminMessage(d.message);load()}
  async function changeAdmin(member:AdminMember,action:string){const reason=window.prompt("Enter the reason for this access change. It will be permanently audited.");if(!reason)return;let accessLevel=member.access_level;if(action==="change_level"){const choice=window.prompt("Enter: platform_owner, case_administrator, or directory_moderator",member.access_level);if(!choice)return;accessLevel=choice}setWorking(member.user_id);const r=await fetch("/api/admin/users/platform",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:member.user_id,action,accessLevel,reason})});const d=await r.json();setWorking(null);if(!r.ok){setAdminMessage(d.error??"Access could not be updated.");return}setAdminMessage(d.message);load()}
  if(error)return <p style={{color:"#B23B2E"}}>{error}</p>;
  const attentionCount=(orgRequests?.length??0)+(submissions?.length??0)+(claims?.length??0)+(claimIssues?.length??0)+lifecycleReviews.length;
  return <div>
    <h1 style={{fontSize:24,color:"#17233C",marginBottom:6}}>Dashboard</h1>
    <p style={{...mutedStyle,marginTop:0}}>Review work that needs attention. Use the sidebar to manage organizations or platform access.</p>
    {attentionCount===0?<div style={{...caseStyle,background:"#DCF0E8",padding:18}}><strong style={{color:"#1E3A5F"}}>You&apos;re all caught up.</strong><div style={{...mutedStyle,fontSize:13,marginTop:4}}>There are no requests, public updates, claims, access cases, or closure reviews waiting.</div></div>:<div style={gridStyle}>{(orgRequests?.length??0)>0&&<Card label="Organization Requests" count={orgRequests?.length} href="/admin/org-requests"/>}{(submissions?.length??0)>0&&<Card label="Pending Public Updates" count={submissions?.length} href="#submissions"/>}{(claims?.length??0)>0&&<Card label="Listing Claims" count={claims?.length} href="#claims"/>}{(claimIssues?.length??0)>0&&<Card label="Access Cases" count={claimIssues?.length} href="#claim-issues"/>}{lifecycleReviews.length>0&&<Card label="Closure & Dormancy" count={lifecycleReviews.length} href="#lifecycle-reviews"/>}</div>}
    {lifecycleReviews.length>0&&<><h2 id="lifecycle-reviews" style={headingStyle}>Closure and dormancy reviews</h2>{lifecycleReviews.map(review=><a key={review.id} href={`/admin/orgs/${review.org_id}`} style={{...itemStyle,display:"block",color:"#1E3A5F",textDecoration:"none"}}><strong>{review.org_name}</strong> · {review.review_type.replaceAll("_"," ")}<div style={{fontSize:13,color:"#6B6862",marginTop:5}}>Status: {review.status.replaceAll("_"," ")} · Review date: {new Date(review.response_due_at).toLocaleDateString()}<br/>{review.reason}</div></a>)}</>}
    {(claimIssues?.length??0)>0&&<h2 id="claim-issues" style={headingStyle}>Organization access cases</h2>}
    {claimIssues?.map(report=>{const overdue=new Date(report.due_at).getTime()<Date.now();return <details key={report.id} open={overdue||report.status==="ready_decision"} style={{...caseStyle,borderColor:overdue?"#E85C56":"#E7E5E1"}}>
      <summary style={{cursor:"pointer",fontWeight:800,color:"#1E3A5F"}}>{report.org_name} · {statusLabel(report.status)} {overdue?"· OVERDUE":""}</summary>
      <div style={{fontSize:13,lineHeight:1.55,marginTop:12}}><strong>Next:</strong> {report.next_action}<br/><strong>Due:</strong> {new Date(report.due_at).toLocaleDateString()}<br/><strong>Reporter:</strong> {report.reporter_name} · {report.reporter_email}{report.reporter_phone?` · ${report.reporter_phone}`:""}<br/><strong>Current owner:</strong> {report.current_owner_email??"No owner email found"}<br/><strong>Issue:</strong> {issueLabel(report.issue_type)} · {report.relationship_to_org.replaceAll("_"," ")}{report.previous_org_email?<><br/><strong>Previous email:</strong> {report.previous_org_email}</>:null}</div>
      <p style={{whiteSpace:"pre-wrap",fontSize:13}}>{report.details}</p>{report.evidence_url&&<a href={report.evidence_url} target="_blank" rel="noreferrer">Open supporting link</a>}
      <div style={{display:"grid",gap:7,margin:"14px 0"}}><Check done={!!report.reporter_evidence_received_at} label="Reporter documentation received" onClick={()=>updateCase(report.id,{checkpoint:"reporter_evidence"})}/><Check done={!!report.owner_response_received_at} label="Current owner response received" onClick={()=>updateCase(report.id,{checkpoint:"owner_response"})}/><Check done={!!report.official_record_checked_at} label="Independent official record checked" onClick={()=>updateCase(report.id,{checkpoint:"official_record"})}/></div>
      <label style={{display:"block",fontSize:12,fontWeight:800}}>Outcome sent to both parties<textarea value={notes[report.id]??""} onChange={e=>setNotes(n=>({...n,[report.id]:e.target.value}))} rows={3} placeholder="Explain the decision and any next steps. Do not include private evidence or personal information." style={textareaStyle}/></label>
      <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:9}}><button disabled={working===report.id} onClick={()=>updateCase(report.id,{status:"resolved",resolutionNotes:notes[report.id]??""})}>Resolve and email outcome</button><button disabled={working===report.id} onClick={()=>updateCase(report.id,{status:"rejected",resolutionNotes:notes[report.id]??""})}>Close without access change</button></div>
    </details>})}
    {(submissions?.length??0)>0&&<><h2 id="submissions" style={headingStyle}>Pending public updates</h2>{submissions?.map(s=><div key={s.id} style={itemStyle}><strong>{s.org_name}</strong> — {s.field_label}<div style={{fontSize:13,margin:"6px 0"}}>{s.old_value} → <strong>{s.new_value}</strong></div><button onClick={()=>act(s.id,"approve")} style={{marginRight:8}}>Approve</button><button onClick={()=>act(s.id,"reject")}>Reject</button></div>)}</>}
    {(claims?.length??0)>0&&<><h2 id="claims" style={headingStyle}>Listing claims needing manual review</h2>{claimActionError&&<div role="alert" style={{...itemStyle,borderColor:"#E85C56",color:"#B23B2E",background:"#FBEFF1"}}>{claimActionError}</div>}{claims?.map(c=><div key={c.id} style={itemStyle}><strong>{c.org_name}</strong><div style={{fontSize:13,margin:"6px 0",color:"#6B6862"}}>Requested by: {c.requester_email}</div><button disabled={working===c.id} onClick={()=>actClaim(c.id,"approve")} style={{marginRight:8}}>{working===c.id?"Working…":"Approve claim"}</button><button disabled={working===c.id} onClick={()=>actClaim(c.id,"reject")}>Reject</button></div>)}</>}
    <h2 id="admin-team" style={headingStyle}>Admin team</h2>
    <details style={caseStyle}><summary style={{cursor:"pointer",fontWeight:800,color:"#E85C56"}}>What each platform access level means</summary><div style={{fontSize:13,lineHeight:1.65,marginTop:12}}><strong>Platform Owner:</strong> Full platform and security oversight. Only this level can invite, change, or suspend platform administrators.<br/><strong>Case Administrator:</strong> Handles ownership claims, access disputes, closure reviews, and support cases. Cannot manage platform administrators.<br/><strong>Directory Moderator:</strong> Reviews routine public directory listings and submitted public updates. Cannot access private evidence, ownership disputes, or private rescue records.<br/><strong>Important:</strong> No platform role automatically grants access to a rescue or shelter&apos;s private Rescue Manager records.</div></details>
    {myAdminLevel==="platform_owner"&&<details style={{...caseStyle,background:"#F2D6DC"}}><summary style={{cursor:"pointer",fontWeight:800,color:"#1E3A5F"}}>Invite a platform administrator</summary><form onSubmit={inviteAdmin} style={{marginTop:14}}><div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:8}}><input type="email" required placeholder="Exact account email" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} style={{padding:10,border:"1px solid #D8D6D2"}}/><select value={inviteLevel} onChange={e=>setInviteLevel(e.target.value)}><option value="directory_moderator">Directory Moderator</option><option value="case_administrator">Case Administrator</option><option value="platform_owner">Platform Owner</option></select></div><button disabled={working==="invite-admin"} style={{marginTop:10}}>{working==="invite-admin"?"Sending…":"Send Secure Invitation"}</button><p style={{fontSize:12}}>The person must already have an active Pack of Five account. The exact-email invitation expires after 24 hours.</p></form></details>}
    {adminMessage&&<p style={{...itemStyle,background:"#DCF0E8"}}>{adminMessage}</p>}
    <details style={caseStyle}><summary style={{cursor:"pointer",fontWeight:800,color:"#1E3A5F"}}>Existing administrators ({adminTeam.length})</summary>{adminTeam.map(member=><div key={member.user_id} style={{borderTop:"1px solid #E7E5E1",padding:"12px 0"}}><strong>{member.email}</strong><div style={{fontSize:13,color:"#6B6862",margin:"4px 0"}}>{adminLevelLabel(member.access_level)} · {member.status}</div>{myAdminLevel==="platform_owner"&&<div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button disabled={working===member.user_id} onClick={()=>changeAdmin(member,"change_level")}>Change level</button><button disabled={working===member.user_id} onClick={()=>changeAdmin(member,member.status==="active"?"suspend":"restore")}>{member.status==="active"?"Suspend":"Restore"}</button></div>}</div>)}</details>
    {myAdminLevel==="platform_owner"&&<details style={caseStyle}><summary style={{cursor:"pointer",fontWeight:800,color:"#1E3A5F"}}>Invitation history ({adminInvites.length})</summary>{adminInvites.map(invite=><div key={invite.id} style={{borderTop:"1px solid #E7E5E1",padding:"10px 0",fontSize:13}}><strong>{invite.email}</strong> · {adminLevelLabel(invite.access_level)} · {invite.status}<br/><span style={mutedStyle}>Expires {new Date(invite.expires_at).toLocaleString()}</span></div>)}</details>}
  </div>
}
function Check({done,label,onClick}:{done:boolean;label:string;onClick:()=>void}){return <button type="button" disabled={done} onClick={onClick} style={{padding:10,textAlign:"left",border:"1px solid #D8E3EA",background:done?"#DCF0E8":"#fff",color:"#1E3A5F",fontWeight:700}}>{done?"✓":"○"} {label}</button>}
function issueLabel(v:string){return({already_claimed:"Organization is already claimed",lost_email_access:"Lost access to organization email",wrong_owner:"Current owner may be incorrect",organization_details_wrong:"Organization information is incorrect",other:"Other issue"}as Record<string,string>)[v]??v}
function statusLabel(v:string){return({waiting_documents:"Waiting for documents",waiting_reporter:"Waiting for reporter",waiting_owner:"Waiting for owner",ready_decision:"Ready for decision",reviewing:"Under review"}as Record<string,string>)[v]??v.replaceAll("_"," ")}
function adminLevelLabel(v:string){return({platform_owner:"Platform Owner",case_administrator:"Case Administrator",directory_moderator:"Directory Moderator"}as Record<string,string>)[v]??v.replaceAll("_"," ")}
function Card({label,count,href}:{label:string;count?:number;href:string}){return <a href={href} style={{display:"block",background:"#fff",border:"1px solid #E7E5E1",borderRadius:9,padding:14,color:"#17233C",textDecoration:"none"}}><div style={{fontSize:13,color:"#6B6862"}}>{label}</div>{typeof count==="number"&&<div style={{fontSize:28,fontWeight:800,marginTop:3}}>{count}</div>}</a>}
const gridStyle={display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(190px, 1fr))",gap:12,margin:"18px 0 26px"}as const;
const headingStyle={fontSize:15,marginTop:28};const mutedStyle={color:"#6B6862"};const itemStyle={border:"1px solid #E7E5E1",borderRadius:6,padding:14,marginBottom:8};const caseStyle={border:"1px solid #E7E5E1",borderRadius:8,padding:14,marginBottom:10,background:"#fff"};const textareaStyle={display:"block",width:"100%",marginTop:5,padding:9,border:"1px solid #D8D6D2",boxSizing:"border-box"}as const;
