"use client";
import {useEffect,useState} from "react";
type Queue={key:string;title:string;description:string;count:number;href:string;urgent?:boolean};
type RecentTransfer={id:string;animal_name:string;transfer_completed_at:string;receiving_organization_name:string|null;transfer_confirmed_by_email:string|null};
const C={navy:"#1E3A5F",coral:"#E85C56",red:"#B93A2E",muted:"#4A5D75",border:"#DCE4EC",mint:"#DCF0E8",peach:"#FBE3DA"};
export default function ShelterExpressDashboard(){
 const [queues,setQueues]=useState<Queue[]>([]),[recentTransfers,setRecentTransfers]=useState<RecentTransfer[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{Promise.all([
  fetch("/api/animals?caseStatus=active&sort=newest",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d.animals??[]}),
  fetch("/api/shelter-express/offers",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d.offers??[]}),
  fetch("/api/fosters/updates",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d.updates??[]}),
  fetch("/api/shelter-express/partners",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d.partners??[]}),
 ]).then(([animals,offers,reports,partners])=>{const urgent=animals.filter((a:{urgency:string|null})=>["urgent","critical"].includes(a.urgency??""));const today=new Date().toISOString().slice(0,10);setQueues([
  {key:"unpublished",title:"Urgent animals not public yet",description:"Finish or publish these urgent listings so rescue partners can see them.",count:urgent.filter((a:{public_share_enabled:boolean})=>!a.public_share_enabled).length,href:"/shelter-express/animals?filter=unpublished",urgent:true},
 {key:"offers",title:"Rescue and tag offers",description:"Review new or ongoing offers connected to urgent animals.",count:offers.filter((o:{status:string})=>["new","reviewing","contacted"].includes(o.status)).length,href:"/shelter-express/offers",urgent:true},
  {key:"awaiting-transfer",title:"Approved tags awaiting transfer",description:"These rescues were approved but have not yet confirmed physical receipt of the animal.",count:offers.filter((o:{status:string;offer_type:string;transfer_completed_at:string|null})=>o.offer_type==="tag_request"&&o.status==="accepted"&&!o.transfer_completed_at).length,href:"/shelter-express/offers?view=accepted",urgent:true},
  {key:"reports",title:"Volunteer reports",description:"Review new updates submitted for animals connected to your shelter.",count:reports.filter((r:{status:string})=>r.status==="submitted").length,href:"/shelter-express/reports"},
  {key:"reviews",title:"Partner reviews due",description:"Revisit private rescue-partner notes and relationship status.",count:partners.filter((p:{next_review_at:string|null})=>p.next_review_at&&p.next_review_at.slice(0,10)<=today).length,href:"/shelter-express/partners?review=due"},
 ].filter(q=>q.count>0));setRecentTransfers((offers as RecentTransfer[]).filter(offer=>Boolean(offer.transfer_completed_at)).sort((a,b)=>new Date(b.transfer_completed_at).getTime()-new Date(a.transfer_completed_at).getTime()).slice(0,5));}).catch(reason=>setError(reason instanceof Error?reason.message:"The dashboard could not be loaded.")).finally(()=>setLoading(false));},[]);
 return <div><p style={eyebrow}>Shelter Express</p><h1 style={title}>Dashboard</h1><p style={intro}>A quick view of work that needs your shelter&apos;s attention.</p>
 {loading?<div style={notice}>Checking your work queues…</div>:null}{error?<div role="alert" style={{...notice,background:C.peach,color:C.red}}>{error}</div>:null}
 {!loading&&!error&&queues.length===0?<section style={caughtUp}><div style={check}>✓</div><div><h2 style={caughtTitle}>You&apos;re all caught up</h2><p style={caughtText}>There are no urgent listings waiting to publish, active offers, approved tags waiting for transfer, new volunteer reports, or partner reviews due.</p></div></section>:null}
 {!loading&&!error&&queues.length>0?<section><h2 style={sectionTitle}>Needs your attention</h2><div style={grid}>{queues.map(q=><a key={q.key} href={q.href} style={{...card,borderLeftColor:q.urgent?C.red:C.coral}}><span style={{...count,color:q.urgent?C.red:C.coral}}>{q.count}</span><span><strong style={cardTitle}>{q.title}</strong><span style={description}>{q.description}</span></span><span aria-hidden="true" style={arrow}>→</span></a>)}</div></section>:null}
 {!loading&&!error&&recentTransfers.length>0?<section><div style={sectionHeading}><h2 style={sectionTitle}>Recently transferred</h2><a href="/shelter-express/archived?view=offers" style={historyLink}>View all retained records</a></div><div style={transferList}>{recentTransfers.map(transfer=><article key={transfer.id} style={transferCard}><div><strong style={cardTitle}>{transfer.animal_name}</strong><span style={description}>Transferred to {transfer.receiving_organization_name||"receiving rescue"}</span><span style={transferMeta}>{new Date(transfer.transfer_completed_at).toLocaleString()}{transfer.transfer_confirmed_by_email?` · Confirmed by ${transfer.transfer_confirmed_by_email}`:""}</span></div><a href="/shelter-express/archived?view=offers" style={secondary}>View record</a></article>)}</div></section>:null}
 <section style={quick}><h2 style={sectionTitle}>Quick actions</h2><div style={actions}><a href="/shelter-express/animals/new" style={primary}>+ Add an urgent animal</a><a href="/shelter-express/animals" style={secondary}>View urgent animals</a><a href="/shelter-express/partners" style={secondary}>Rescue partners</a></div></section></div>;
}
const eyebrow:React.CSSProperties={margin:"0 0 8px",color:C.coral,fontSize:12,fontWeight:800,letterSpacing:".1em",textTransform:"uppercase"},title:React.CSSProperties={margin:0,color:C.navy,fontSize:42},intro:React.CSSProperties={margin:"10px 0 24px",color:C.muted,fontSize:17},notice:React.CSSProperties={padding:20,border:`1px solid ${C.border}`,color:C.navy},caughtUp:React.CSSProperties={display:"flex",alignItems:"center",gap:18,padding:24,background:C.mint,border:`1px solid ${C.border}`},check:React.CSSProperties={display:"grid",placeItems:"center",width:48,height:48,borderRadius:"50%",background:C.navy,color:"#fff",fontSize:26,fontWeight:800,flex:"0 0 auto"},caughtTitle:React.CSSProperties={margin:"0 0 5px",color:C.navy,fontSize:25},caughtText:React.CSSProperties={margin:0,color:C.muted,lineHeight:1.5},sectionTitle:React.CSSProperties={color:C.navy,fontSize:24,margin:"26px 0 14px"},grid:React.CSSProperties={display:"grid",gap:12},card:React.CSSProperties={display:"grid",gridTemplateColumns:"52px minmax(0,1fr) auto",alignItems:"center",gap:14,padding:17,background:"#fff",border:`1px solid ${C.border}`,borderLeft:"5px solid",textDecoration:"none"},count:React.CSSProperties={fontSize:30,fontWeight:800,textAlign:"center"},cardTitle:React.CSSProperties={display:"block",color:C.navy,fontSize:18},description:React.CSSProperties={display:"block",marginTop:4,color:C.muted,lineHeight:1.45},arrow:React.CSSProperties={color:C.navy,fontSize:23,fontWeight:800},quick:React.CSSProperties={marginTop:28,borderTop:`1px solid ${C.border}`},actions:React.CSSProperties={display:"flex",gap:9,flexWrap:"wrap"},primary:React.CSSProperties={padding:"11px 15px",background:C.navy,color:"#fff",fontWeight:800,textDecoration:"none"},secondary:React.CSSProperties={...primary,background:"#fff",color:C.navy,border:`1px solid ${C.border}`};
const sectionHeading:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"baseline",gap:12,flexWrap:"wrap"},historyLink:React.CSSProperties={color:C.navy,fontWeight:800},transferList:React.CSSProperties={display:"grid",gap:10},transferCard:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:14,flexWrap:"wrap",padding:16,background:"#fff",border:`1px solid ${C.border}`,borderLeft:`5px solid ${C.coral}`},transferMeta:React.CSSProperties={display:"block",marginTop:5,color:C.muted,fontSize:12};
