"use client";
import { useEffect,useMemo,useState } from "react";
type Animal={id:string;name:string|null;temporary_name:string|null;species:string|null;breed_or_type:string|null;urgency:string|null;placement:string|null;public_share_enabled:boolean;photo_url:string|null;open_help_offers:number|string};
const C={navy:"#1E3A5F",coral:"#E85C56",red:"#B93A2E",muted:"#4A5D75",border:"#DCE4EC",mint:"#DCF0E8",pink:"#F2D6DC"};
export default function ShelterExpressPage(){
 const [animals,setAnimals]=useState<Animal[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState<"all"|"critical"|"urgent"|"unpublished">("all");
 useEffect(()=>{fetch("/api/auth/me",{cache:"no-store"}).then(r=>r.json()).then(async auth=>{const portals=Array.isArray(auth.user?.availablePortals)?auth.user.availablePortals:[];if(!auth.user||!portals.includes("shelter")){window.location.replace("/login?portal=shelter");return;}const response=await fetch("/api/animals?caseStatus=active&sort=newest",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error??"Urgent animals could not be loaded.");setAnimals(Array.isArray(data.animals)?data.animals:[]);}).catch(reason=>setError(reason instanceof Error?reason.message:"Urgent animals could not be loaded.")).finally(()=>setLoading(false));},[]);
 const urgent=useMemo(()=>animals.filter(a=>a.urgency==="urgent"||a.urgency==="critical"),[animals]);
 const counts={all:urgent.length,critical:urgent.filter(a=>a.urgency==="critical").length,urgent:urgent.filter(a=>a.urgency==="urgent").length,unpublished:urgent.filter(a=>!a.public_share_enabled).length};
 const visible=useMemo(()=>urgent.filter(a=>filter==="all"||(filter==="unpublished"?!a.public_share_enabled:a.urgency===filter)).filter(a=>`${a.name??""} ${a.temporary_name??""} ${a.species??""} ${a.breed_or_type??""} ${a.placement??""}`.toLowerCase().includes(query.toLowerCase())),[urgent,filter,query]);
 return <div><div style={heading}><div><p style={eyebrow}>Shelter Express</p><h1 style={title}>Urgent Animals</h1><p style={intro}>A focused working list of animals your shelter is actively sharing for rescue intervention.</p></div><a href="/shelter-express/animals/new" style={primary}>+ Add an urgent animal</a></div>
 <section style={stats}><Stat value={counts.all} label="Active urgent listings"/><Stat value={counts.critical} label="Critical" danger/><Stat value={counts.unpublished} label="Not public yet"/></section>
 <section style={tools}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, shelter ID, breed, or placement" style={search}/><div style={filters}>{(["all","critical","urgent","unpublished"] as const).map(key=><button key={key} onClick={()=>setFilter(key)} style={{...filterButton,...(filter===key?activeFilter:{})}}>{key==="all"?"All":key==="unpublished"?"Not public":key[0].toUpperCase()+key.slice(1)} ({counts[key]})</button>)}</div></section>
 {loading?<div style={notice}>Loading urgent animals…</div>:null}{error?<div role="alert" style={{...notice,background:"#FBE3DA",color:C.red}}>{error}</div>:null}{!loading&&!error&&urgent.length===0?<section style={{...notice,background:C.mint}}><h2 style={{margin:"0 0 6px",color:C.navy,fontSize:21}}>No urgent animals are currently listed.</h2><p style={{margin:0,color:C.muted}}>Use Quick Add when an animal needs rescue intervention. You only need the essential information to begin.</p></section>:null}
 {!loading&&!error&&urgent.length>0&&visible.length===0?<div style={notice}>No urgent animals match these filters.</div>:null}
 <div style={{display:"grid",gap:14}}>{visible.map(a=><AnimalCard key={a.id} animal={a}/>)}</div></div>;
}
function Stat({value,label,danger=false}:{value:number;label:string;danger?:boolean}){return <div style={stat}><strong style={{fontSize:30,color:danger?C.red:C.navy}}>{value}</strong><span style={{color:C.muted}}>{label}</span></div>}
function AnimalCard({animal:a}:{animal:Animal}){const name=a.name||a.temporary_name||"Unnamed animal",offers=Number(a.open_help_offers||0),critical=a.urgency==="critical";return <article style={{...card,borderLeftColor:critical?C.red:C.coral}}>{a.photo_url?<img src={a.photo_url} alt="" style={photo}/>:<div style={{...photo,display:"grid",placeItems:"center",background:"#F4F6F8",fontSize:30}}>🐾</div>}<div style={{minWidth:0,flex:1}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h2 style={{margin:0,color:C.navy,fontSize:22}}>{name}</h2><p style={{margin:"5px 0",color:C.muted}}>{[a.species,a.breed_or_type].filter(Boolean).join(" · ")||"Animal details pending"}</p></div><span style={{...badge,color:critical?C.red:C.coral,background:critical?"#F8DFDC":"#FFE7DE"}}>{critical?"Critical":"Urgent"}</span></div><div style={details}><span><strong>Placement:</strong> {a.placement?.replaceAll("_"," ")||"Needs rescue"}</span><span><strong>Public profile:</strong> {a.public_share_enabled?"Active":"Not published"}</span><span><strong>Offers:</strong> {offers}</span></div><div style={actions}>{a.public_share_enabled?<a href={`/pet/${a.id}`} style={secondary}>View public profile</a>:null}{offers>0?<a href="/shelter-express/offers" style={primary}>Review {offers} offer{offers===1?"":"s"}</a>:null}</div></div></article>}
const eyebrow:React.CSSProperties={margin:"0 0 8px",color:C.coral,fontSize:12,fontWeight:800,letterSpacing:".1em",textTransform:"uppercase"};const title:React.CSSProperties={margin:0,color:C.navy,fontSize:42,lineHeight:1.05};const intro:React.CSSProperties={margin:"10px 0 0",maxWidth:680,color:C.muted,fontSize:16,lineHeight:1.55};const heading:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"end",gap:18,flexWrap:"wrap",marginBottom:24};const primary:React.CSSProperties={display:"inline-block",padding:"11px 15px",background:C.navy,color:"#fff",textDecoration:"none",fontWeight:800,border:0,cursor:"pointer"};const secondary:React.CSSProperties={...primary,background:"#fff",color:C.navy,border:`1px solid ${C.border}`};const stats:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:12,marginBottom:18};const stat:React.CSSProperties={display:"grid",gap:2,padding:16,background:"#fff",border:`1px solid ${C.border}`};const tools:React.CSSProperties={padding:16,background:"#fff",border:`1px solid ${C.border}`,marginBottom:18};const search:React.CSSProperties={width:"100%",boxSizing:"border-box",padding:12,border:`1px solid ${C.border}`,fontSize:15,marginBottom:12};const filters:React.CSSProperties={display:"flex",gap:8,flexWrap:"wrap"};const filterButton:React.CSSProperties={padding:"8px 11px",background:"#fff",color:C.navy,border:`1px solid ${C.border}`,fontWeight:700,cursor:"pointer"};const activeFilter:React.CSSProperties={background:C.navy,color:"#fff"};const notice:React.CSSProperties={padding:20,background:"#fff",border:`1px solid ${C.border}`,color:C.muted};const card:React.CSSProperties={display:"flex",gap:16,padding:16,background:"#fff",border:`1px solid ${C.border}`,borderLeft:"5px solid",alignItems:"flex-start"};const photo:React.CSSProperties={width:100,height:100,objectFit:"cover",borderRadius:7,flex:"0 0 auto"};const badge:React.CSSProperties={padding:"5px 9px",fontSize:11,fontWeight:800,textTransform:"uppercase"};const details:React.CSSProperties={display:"flex",gap:"8px 20px",flexWrap:"wrap",color:C.muted,fontSize:14,marginTop:10};const actions:React.CSSProperties={display:"flex",gap:8,flexWrap:"wrap",marginTop:14};
