import { NextRequest, NextResponse } from "next/server";
import { AuthError, requireEffectiveOrg } from "@/lib/auth";
import { sql } from "@/lib/db";
export const runtime="edge";export const dynamic="force-dynamic";

function failure(error:unknown,message:string){return error instanceof AuthError?NextResponse.json({error:error.message},{status:error.status}):NextResponse.json({error:message},{status:500});}

export async function GET(){try{const {orgId}=await requireEffectiveOrg();
 const partners=await sql`select relationship.id as relationship_id,organization.id,organization.name,organization.org_type,organization.city,organization.county,organization.state,organization.species,organization.intake_status,organization.website,organization.public_email,relationship.relationship_status,relationship.private_notes,relationship.primary_contact,relationship.last_worked_with_at,relationship.next_review_at,relationship.created_at from shelter_rescue_partners relationship join organizations organization on organization.id=relationship.rescue_org_id where relationship.shelter_org_id=${orgId}::uuid and relationship.archived_at is null and organization.archived_at is null order by case relationship.relationship_status when 'preferred' then 0 when 'approved' then 1 when 'vetting' then 2 when 'considering' then 3 when 'on_hold' then 4 else 5 end,organization.name`;
 const archivedPartners=await sql`select relationship.id as relationship_id,organization.id,organization.name,organization.org_type,organization.city,organization.county,organization.state,relationship.relationship_status,relationship.private_notes,relationship.primary_contact,relationship.last_worked_with_at,relationship.next_review_at,relationship.archived_at,relationship.archive_reason,account.email as archived_by_email from shelter_rescue_partners relationship join organizations organization on organization.id=relationship.rescue_org_id left join users account on account.id=relationship.archived_by where relationship.shelter_org_id=${orgId}::uuid and relationship.archived_at is not null order by relationship.archived_at desc`;
 const candidates=await sql`select organization.id,organization.name,organization.org_type,organization.city,organization.county,organization.state,organization.species,organization.intake_status,organization.website,organization.public_email from organizations organization where organization.archived_at is null and organization.id<>${orgId}::uuid and coalesce(organization.org_type,'') not in ('Municipal Shelter','Private Shelter','Animal Control','Shelter') and not exists(select 1 from shelter_rescue_partners relationship where relationship.shelter_org_id=${orgId}::uuid and relationship.rescue_org_id=organization.id) order by organization.name`;
 return NextResponse.json({partners,archivedPartners,candidates});}catch(error){return failure(error,"Rescue partners could not be loaded.");}}

export async function POST(request:NextRequest){try{const {session,orgId}=await requireEffectiveOrg();const body=await request.json().catch(()=>null);const rescueOrgId=typeof body?.rescueOrgId==="string"?body.rescueOrgId:"";if(!rescueOrgId)return NextResponse.json({error:"Choose an organization."},{status:400});const rows=await sql`insert into shelter_rescue_partners(shelter_org_id,rescue_org_id,added_by,relationship_status) select ${orgId}::uuid,organization.id,${session.id}::uuid,'considering' from organizations organization where organization.id=${rescueOrgId}::uuid and organization.archived_at is null and organization.id<>${orgId}::uuid and coalesce(organization.org_type,'') not in ('Municipal Shelter','Private Shelter','Animal Control','Shelter') on conflict(shelter_org_id,rescue_org_id) do nothing returning id`;if(!rows[0])return NextResponse.json({error:"That organization is already saved or archived."},{status:409});return NextResponse.json({message:"Rescue partner added for consideration."},{status:201});}catch(error){return failure(error,"The rescue partner could not be added.");}}

// A remove request archives the record; it never deletes relationship history.
export async function DELETE(request:NextRequest){try{const {session,orgId}=await requireEffectiveOrg();const body=await request.json().catch(()=>null);const rescueOrgId=typeof body?.rescueOrgId==="string"?body.rescueOrgId:"";if(!rescueOrgId)return NextResponse.json({error:"Choose a rescue partner."},{status:400});const rows=await sql`update shelter_rescue_partners set archived_at=now(),archived_by=${session.id}::uuid,archive_reason='Removed from active partner list',updated_at=now() where shelter_org_id=${orgId}::uuid and rescue_org_id=${rescueOrgId}::uuid and archived_at is null returning id`;if(!rows[0])return NextResponse.json({error:"Active rescue partner not found."},{status:404});return NextResponse.json({message:"Rescue partner archived. Its private history was preserved."});}catch(error){return failure(error,"The rescue partner could not be archived.");}}

export async function PATCH(request:NextRequest){try{const {orgId}=await requireEffectiveOrg();const body=await request.json().catch(()=>null);const rescueOrgId=typeof body?.rescueOrgId==="string"?body.rescueOrgId:"";if(!rescueOrgId)return NextResponse.json({error:"Choose a rescue partner."},{status:400});
 if(body?.action==="restore"){const rows=await sql`update shelter_rescue_partners set archived_at=null,archived_by=null,archive_reason=null,updated_at=now() where shelter_org_id=${orgId}::uuid and rescue_org_id=${rescueOrgId}::uuid and archived_at is not null returning id`;if(!rows[0])return NextResponse.json({error:"Archived rescue partner not found."},{status:404});return NextResponse.json({message:"Rescue partner restored to the active list."});}
 const relationshipStatus=typeof body?.relationshipStatus==="string"?body.relationshipStatus:"considering",privateNotes=typeof body?.privateNotes==="string"?body.privateNotes.trim().slice(0,5000):"",primaryContact=typeof body?.primaryContact==="string"?body.primaryContact.trim().slice(0,500):"",lastWorkedWithAt=typeof body?.lastWorkedWithAt==="string"&&body.lastWorkedWithAt?body.lastWorkedWithAt:null,nextReviewAt=typeof body?.nextReviewAt==="string"&&body.nextReviewAt?body.nextReviewAt:null;
 if(!["considering","vetting","approved","preferred","on_hold","do_not_use"].includes(relationshipStatus))return NextResponse.json({error:"Choose a valid relationship status."},{status:400});if(["on_hold","do_not_use"].includes(relationshipStatus)&&!privateNotes)return NextResponse.json({error:"Add a private note explaining why this partner is on hold or should not be used."},{status:400});const rows=await sql`update shelter_rescue_partners set relationship_status=${relationshipStatus},private_notes=${privateNotes||null},primary_contact=${primaryContact||null},last_worked_with_at=${lastWorkedWithAt}::date,next_review_at=${nextReviewAt}::date,updated_at=now() where shelter_org_id=${orgId}::uuid and rescue_org_id=${rescueOrgId}::uuid and archived_at is null returning id`;if(!rows[0])return NextResponse.json({error:"Active rescue partner not found."},{status:404});return NextResponse.json({message:"Private partner details saved."});}catch(error){return failure(error,"Private partner details could not be saved.");}}
