"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";

type Animal={
  id:string;name:string|null;temporary_name:string|null;species:string|null;breed_or_type:string|null;
  urgency:string|null;public_share_enabled:boolean;public_summary:string|null;public_need:string|null;
  external_listing_url:string|null;outcome_status:string|null;outcome_date:string|null;public_outcome_message:string|null;
};
const C={navy:"#1E3A5F",coral:"#E85C56",muted:"#4A5D75",border:"#DCE4EC",mint:"#DCF0E8",peach:"#FBE3DA"};

export default function ManageShelterAnimalPage(){
  const params=useParams();const id=String(params?.id??"");
  const [animal,setAnimal]=useState<Animal|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [name,setName]=useState(""),[shelterId,setShelterId]=useState(""),[species,setSpecies]=useState("Dog"),[breed,setBreed]=useState(""),[urgency,setUrgency]=useState("urgent"),[summary,setSummary]=useState(""),[need,setNeed]=useState(""),[externalUrl,setExternalUrl]=useState(""),[published,setPublished]=useState(false),[outcome,setOutcome]=useState("transferred"),[outcomeMessage,setOutcomeMessage]=useState("");

  useEffect(()=>{fetch(`/api/animals/${encodeURIComponent(id)}`,{cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error??"Listing could not be loaded.");const value=data.animal as Animal;setAnimal(value);setName(value.name??"");setShelterId(value.temporary_name??"");setSpecies(value.species??"Dog");setBreed(value.breed_or_type??"");setUrgency(value.urgency??"urgent");setSummary(value.public_summary??"");setNeed(value.public_need??"");setExternalUrl(value.external_listing_url??"");setPublished(Boolean(value.public_share_enabled));setOutcome(value.outcome_status??"transferred");setOutcomeMessage(value.public_outcome_message??"");}).catch(reason=>setError(reason instanceof Error?reason.message:"Listing could not be loaded.")).finally(()=>setLoading(false));},[id]);

  async function patch(body:Record<string,unknown>,success:string){
    setSaving(true);setError("");setMessage("");
    try{const response=await fetch(`/api/animals/${encodeURIComponent(id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error??"The listing could not be updated.");setAnimal(data.animal);setPublished(Boolean(data.animal.public_share_enabled));setMessage(success);}
    catch(reason){setError(reason instanceof Error?reason.message:"The listing could not be updated.");}
    finally{setSaving(false);}
  }

  function save(event:React.FormEvent){event.preventDefault();void patch({name,temporaryName:shelterId,species,breedOrType:breed,urgency,publicSummary:summary,publicNeed:need,externalListingUrl:externalUrl||null,publicShareEnabled:published,publicSyncFields:["name","species","breed_or_type"]},"Urgent listing updated.");}
  async function close(){if(!window.confirm("Close this urgent listing? It will be removed from public view and kept in Resolved listings."))return;setSaving(true);setError("");setMessage("");try{const outcomeDate=new Date().toISOString().slice(0,10);const response=await fetch(`/api/animals/${encodeURIComponent(id)}/outcome`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({outcomeType:outcome,outcomeDate,notes:outcomeMessage||null})});const data=await response.json();if(!response.ok)throw new Error(data.error??"The listing could not be closed.");await patch({publicOutcomeMessage:outcomeMessage||null,publicShareEnabled:false},"Listing closed and moved to Resolved.");}catch(reason){setError(reason instanceof Error?reason.message:"The listing could not be closed.");setSaving(false);}}
  async function reopen(){setSaving(true);setError("");setMessage("");try{const response=await fetch(`/api/animals/${encodeURIComponent(id)}/outcome`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Urgent shelter listing reopened"})});const data=await response.json();if(!response.ok)throw new Error(data.error??"The listing could not be reopened.");await patch({publicOutcomeMessage:null,urgency,publicShareEnabled:published},"Urgent listing reopened. The previous resolution remains in its history.");}catch(reason){setError(reason instanceof Error?reason.message:"The listing could not be reopened.");setSaving(false);}}
  async function copyShare(kind:"link"|"post"){
    const publicUrl=`${window.location.origin}/pet/${encodeURIComponent(id)}`;
    const animalName=name||shelterId||"This urgent animal";
    const details=[species,breed].filter(Boolean).join(" · ");
    const post=[`URGENT: ${animalName} needs help`,details,need||summary,`View the full listing and offer help: ${publicUrl}`].filter(Boolean).join("\n\n");
    try{await navigator.clipboard.writeText(kind==="link"?publicUrl:post);setError("");setMessage(kind==="link"?"Public link copied.":"Social post copied and ready to share.");}
    catch{setError("Your browser could not copy this automatically. Open the public profile and copy its address instead.");}
  }

  if(loading)return <div style={notice}>Loading listing…</div>;
  if(!animal)return <div role="alert" style={{...notice,background:C.peach}}>{error||"Listing not found."}</div>;
  const resolved=Boolean(animal.outcome_status);
  return <div><a href="/shelter-express/animals" style={back}>← Back to urgent animals</a><p style={eyebrow}>Shelter Express</p><h1 style={title}>{name||shelterId||"Urgent animal"}</h1><p style={intro}>{resolved?"This listing is resolved and no longer appears publicly. You can review it or reopen it.":"Update the public urgent listing without creating a full shelter-management record."}</p>
    {error?<div role="alert" style={{...notice,background:C.peach,color:"#A9362B"}}>{error}</div>:null}{message?<div role="status" style={{...notice,background:C.mint}}>{message}</div>:null}
    {resolved?<section style={{...panel,background:C.mint}}><h2 style={sectionTitle}>Resolved: {animal.outcome_status?.replaceAll("_"," ")}</h2><p style={smallText}>{animal.outcome_date?`Closed ${new Date(animal.outcome_date).toLocaleDateString()}.`:"This listing is closed."} {animal.public_outcome_message}</p><button onClick={reopen} disabled={saving} style={primary}>Reopen urgent listing</button></section>:null}
    {published&&!resolved?<section style={{...panel,background:C.mint}}><h2 style={sectionTitle}>Share this urgent animal</h2><p style={smallText}>Copy a ready-to-use link or social post without retyping the animal&apos;s details.</p><div style={{display:"flex",gap:9,flexWrap:"wrap"}}><button type="button" onClick={()=>void copyShare("post")} style={primary}>Copy social post</button><button type="button" onClick={()=>void copyShare("link")} style={{...primary,background:"#fff",color:C.navy,border:`1px solid ${C.border}`}}>Copy public link</button><a href={`/pet/${encodeURIComponent(id)}`} target="_blank" rel="noreferrer" style={{...primary,background:"#fff",color:C.navy,border:`1px solid ${C.border}`,textDecoration:"none"}}>View public profile</a></div></section>:null}
    <form onSubmit={save} style={panel}><h2 style={sectionTitle}>Listing details</h2><div style={twoColumns}><label style={label}>Name or nickname<input value={name} onChange={e=>setName(e.target.value)} style={input}/></label><label style={label}>Shelter ID<input value={shelterId} onChange={e=>setShelterId(e.target.value)} style={input}/></label></div><div style={twoColumns}><label style={label}>Species<select value={species} onChange={e=>setSpecies(e.target.value)} style={input}><option>Dog</option><option>Cat</option><option>Other</option></select></label><label style={label}>Urgency<select value={urgency} onChange={e=>setUrgency(e.target.value)} style={input}><option value="urgent">Urgent</option><option value="critical">Critical</option></select></label></div><label style={label}>Breed or description<input value={breed} onChange={e=>setBreed(e.target.value)} style={input}/></label><label style={label}>Public summary<textarea rows={3} value={summary} onChange={e=>setSummary(e.target.value)} style={input}/></label><label style={label}>What help is needed?<textarea rows={5} value={need} onChange={e=>setNeed(e.target.value)} style={input}/></label><label style={label}>External shelter listing URL<input type="url" value={externalUrl} onChange={e=>setExternalUrl(e.target.value)} placeholder="https://" style={input}/></label><label style={checkLabel}><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/> Publish this urgent listing publicly</label><button type="submit" disabled={saving} style={primary}>{saving?"Saving…":"Save listing"}</button></form>
    {!resolved?<section style={{...panel,borderColor:"#E9B9B4"}}><h2 style={sectionTitle}>Close urgent listing</h2><p style={smallText}>Use this when the animal no longer needs an active urgent listing. Closing does not transfer legal custody.</p><label style={label}>Resolution<select value={outcome} onChange={e=>setOutcome(e.target.value)} style={input}><option value="transferred">Transferred to rescue</option><option value="adopted">Adopted</option><option value="returned_to_owner">Returned to owner</option><option value="no_longer_urgent">No longer urgent</option><option value="euthanized">Euthanized</option><option value="other">Other</option></select></label><label style={label}>Optional public outcome message<textarea rows={3} value={outcomeMessage} onChange={e=>setOutcomeMessage(e.target.value)} style={input}/></label><button type="button" onClick={close} disabled={saving} style={danger}>Close and unpublish listing</button></section>:null}
  </div>;
}

const back:React.CSSProperties={display:"inline-block",marginBottom:22,color:C.coral,fontWeight:800,textDecoration:"none"};const eyebrow:React.CSSProperties={margin:"0 0 8px",color:C.coral,fontSize:12,fontWeight:800,letterSpacing:".1em",textTransform:"uppercase"};const title:React.CSSProperties={margin:0,color:C.navy,fontSize:38};const intro:React.CSSProperties={maxWidth:760,color:C.muted,lineHeight:1.6};const notice:React.CSSProperties={padding:16,border:`1px solid ${C.border}`,color:C.navy,margin:"16px 0"};const panel:React.CSSProperties={display:"grid",gap:15,maxWidth:780,marginTop:22,padding:20,border:`1px solid ${C.border}`,background:"#fff"};const sectionTitle:React.CSSProperties={margin:0,color:C.navy,fontSize:22};const smallText:React.CSSProperties={margin:0,color:C.muted,lineHeight:1.5};const twoColumns:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:14};const label:React.CSSProperties={display:"grid",gap:6,color:C.navy,fontSize:13,fontWeight:800};const input:React.CSSProperties={width:"100%",boxSizing:"border-box",padding:"10px 11px",border:`1px solid ${C.border}`,background:"#fff",color:C.navy,font:"inherit"};const checkLabel:React.CSSProperties={display:"flex",gap:8,alignItems:"center",color:C.navy,fontWeight:800};const primary:React.CSSProperties={justifySelf:"start",padding:"11px 16px",border:0,background:C.navy,color:"#fff",fontWeight:800,cursor:"pointer"};const danger:React.CSSProperties={...primary,background:"#A9362B"};
