"use client";
import { useEffect,useMemo,useState } from "react";
type Org={id:string;name:string;org_type:string|null;city:string|null;county:string|null;state:string|null;species:string[]|null;intake_status:string|null;website:string|null;public_email:string|null};
const C={navy:"#1E3A5F",coral:"#E85C56",muted:"#4A5D75",border:"#DCE4EC",mint:"#DCF0E8",pink:"#F2D6DC"};
export default function PartnersPage(){
 const [partners,setPartners]=useState<Org[]>([]),[candidates,setCandidates]=useState<Org[]>([]),[query,setQuery]=useState(""),[showAdd,setShowAdd]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setError("");const r=await fetch("/api/shelter-express/partners",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setPartners(d.partners??[]);setCandidates(d.candidates??[]);}
 useEffect(()=>{void load().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 const results=useMemo(()=>candidates.filter(o=>`${o.name} ${o.city??""} ${o.county??""} ${(o.species??[]).join(" ")}`.toLowerCase().includes(query.toLowerCase())).slice(0,30),[candidates,query]);
 async function change(rescueOrgId:string,method:"POST"|"DELETE"){const r=await fetch("/api/shelter-express/partners",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({rescueOrgId})});const d=await r.json();if(!r.ok){setError(d.error);return}await load();}
 return <div><p style={eyebrow}>Your network</p><div style={headingRow}><div><h1 style={title}>Rescue Partners</h1><p style={intro}>Keep a focused list of rescues your shelter trusts, regularly works with, or wants to contact first.</p></div><button onClick={()=>setShowAdd(v=>!v)} style={primary}>{showAdd?"Close search":"+ Add a rescue partner"}</button></div>
 {error?<div role="alert" style={errorStyle}>{error}</div>:null}
 {showAdd?<section style={addPanel}><h2 style={{margin:"0 0 6px",color:C.navy}}>Find a rescue</h2><p style={{margin:"0 0 14px",color:C.muted}}>Search the Pack of Five directory, then intentionally add it to your partner list.</p><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search rescue name, location, or species" style={search}/><div style={{display:"grid",gap:9}}>{results.map(o=><div key={o.id} style={compactCard}><div><strong style={{color:C.navy}}>{o.name}</strong><div style={meta}>{[o.city,o.county,o.state].filter(Boolean).join(" · ")||o.org_type}</div></div><button onClick={()=>change(o.id,"POST")} style={smallButton}>Add partner</button></div>)}</div>{results.length===0?<p style={{color:C.muted}}>No matching rescue organizations found.</p>:null}</section>:null}
 <h2 style={{color:C.navy,marginTop:26}}>Your saved partners ({partners.length})</h2>{loading?<div style={notice}>Loading partners…</div>:null}{!loading&&partners.length===0?<div style={{...notice,background:C.mint}}><strong>No rescue partners added yet.</strong><div style={{marginTop:5}}>Add the rescues your shelter works with most often so useful contacts stay easy to find.</div></div>:null}<div style={{display:"grid",gap:12}}>{partners.map(o=><article key={o.id} style={card}><h3 style={{margin:0,color:C.navy,fontSize:20}}>{o.name}</h3><p style={meta}>{[o.org_type,o.city,o.county,o.state].filter(Boolean).join(" · ")}</p><p style={{color:C.muted}}>{o.intake_status||"Contact rescue to confirm current capacity."}</p><div style={{display:"flex",gap:9,flexWrap:"wrap"}}>{o.public_email?<a href={`mailto:${o.public_email}`} style={primary}>Email rescue</a>:null}{o.website?<a href={o.website} target="_blank" rel="noreferrer" style={secondary}>Visit website</a>:null}<button onClick={()=>change(o.id,"DELETE")} style={remove}>Remove</button></div></article>)}</div></div>;
}
const eyebrow:React.CSSProperties={margin:"0 0 8px",color:C.coral,fontWeight:800,fontSize:12,letterSpacing:".1em",textTransform:"uppercase"};const title:React.CSSProperties={margin:0,color:C.navy,fontSize:38};const intro:React.CSSProperties={margin:"9px 0 0",color:C.muted,lineHeight:1.6,maxWidth:650};const headingRow:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"end",gap:18,flexWrap:"wrap",marginBottom:22};const primary:React.CSSProperties={padding:"10px 14px",border:0,background:C.navy,color:"#fff",fontWeight:800,textDecoration:"none",cursor:"pointer"};const secondary:React.CSSProperties={...primary,background:"#fff",color:C.navy,border:`1px solid ${C.border}`};const remove:React.CSSProperties={...secondary,color:"#A33"};const addPanel:React.CSSProperties={padding:18,background:C.pink,border:`1px solid ${C.border}`,marginBottom:22};const search:React.CSSProperties={width:"100%",boxSizing:"border-box",padding:12,border:`1px solid ${C.border}`,fontSize:15,marginBottom:12};const compactCard:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,padding:12,background:"#fff",border:`1px solid ${C.border}`};const smallButton:React.CSSProperties={...primary,padding:"8px 11px",whiteSpace:"nowrap"};const card:React.CSSProperties={padding:18,border:`1px solid ${C.border}`,background:"#fff"};const meta:React.CSSProperties={margin:"5px 0",color:C.muted};const notice:React.CSSProperties={padding:20,border:`1px solid ${C.border}`,color:C.navy};const errorStyle:React.CSSProperties={padding:16,background:"#FBE3DA",color:"#B93A2E",marginBottom:14};
